### ISSUE TITLE
not sure whats wrong ....... but this is what happens with a make install

### ISSUE THREAD

**Issue by ghost** [vedetta-com/dithematic#2]
missing: ./etc/ssl/dns/*.DNSKEY
missing: ./etc/ssl/dns/private/*.*SK
missing: ./etc/ssl/dns/private/tsig.*
missing: ./usr/local/bin/nsec3salt
missing: ./var/unbound/db/root.key
missing: ./var/unbound/etc/root.hints

**Comment by horia** [comment]
mtree(8) messages for files which are missing from the file hierarchy:
`/etc/ssl/dns/*` safe to ignore on fresh install
`/var/unbound/*` populated on first run (fixed)
`/usr/local/bin/nsec3salt` missing (fixed)

Thank you
