### ISSUE TITLE
Makefile.local

### ISSUE THREAD

**Issue by erictwo** [vedetta-com/dithematic#6]
I have 2 VPS from Vultr NS1 (Master) and NS2 (Slave). How do I fill in the overrides for NS2 in the Makefile.local, do I leave the MASTER and MASTER_HOST blank to designate that NS2 is slave? Is the slave set up with the same exact procedure as the master other than different overrides in Makefile.local. Thanks

**Comment by horia** [comment]
It's not clear, but the only change for slave role is `MASTER=no` while using the same procedure.
```console
MASTER =      no
MASTER_HOST = ns1
```
